### ISSUE TITLE
WinTools TP Plugin feature request. 

### ISSUE THREAD

**Issue by Woodsybrah** [KillerBOSS2019/TP-Speed-Test-Plugin#3]
Hi KillerBOSS2019. 

Just wondering if you could add a feature to your WinTools TP plugin if possible?

Not really sure how to explain this in the best way but essentially what I want to do is press a button and turn my screens off. 

The option in windows is under:
Settings/System/Power & sleep/Screen

Thanks in advance.

**Comment by DamienStaebler** [comment]
I'll check if this is possible

**Comment by Woodsybrah** [comment]
Thank you
