### ISSUE TITLE
Can't find the download place

### ISSUE THREAD

**Issue by Yeze12** [KillerBOSS2019/TP-Speed-Test-Plugin#7]
I just can't see where it's supposed to download the plugin. It's one of my first times using GitHub so i don't know exactly what is going on 😂

**Comment by DamienStaebler** [comment]
https://github.com/KillerBOSS2019/TP-Speed-Test-Plugin/releases/tag/2.0.3

That's the latest one. You may need to scroll down a little until you see assets. Then you will see 3 file attached that ends with .tpp download right one for your system.

**Comment by Yeze12** [comment]
Thank you! And sorry for not understanding GitHub 😂
